
### Index
GET http://localhost:3000/products
#Authorization: Bearer 

### Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name" : "coffee",
  "price" : 2,
  "image_url" : "none", 
  "description" : "roasted and toasty",
  "inventory" : "100"
}

### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Britney Foor",
  "email": "britney.k.foor@gmail.com",
  "password": "b43127nk",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Order index
GET http://localhost:3000/orders

### Order create
POST http://localhost:3000/orders
Content-Type: application/json

{
  "user_id": "",
  "product_id": "",
  "quantity": "",
  "sub_total": "",
  "tax": "",
  "total": ""
}

### Order show
GET http://localhost:3000/orders/1

###